version: 1.0

jobs:
  build:
    os: linux-ubuntu
    steps:
      - script:
          name: Install JDK 22
          inputs:
            script: |
              # Download JDK 22
              wget -O /tmp/jdk-22.tar.gz https://download.java.net/java/early_access/jdk22/6/GPL/openjdk-22-ea+6_linux-x64_bin.tar.gz

              # Extract JDK 22
              sudo tar xf /tmp/jdk-22.tar.gz -C /usr/local/

              # Set JAVA_HOME environment variable
              export JAVA_HOME=/usr/local/jdk-22
              export PATH=$PATH:$JAVA_HOME/bin

              # Verify Java installation
              java -version
